#!/bin/bash

DOCKER_USER=denverdino

CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o bin/lxcfs-admission-webhook
sudo docker build --no-cache -t registry.cn-hangzhou.aliyuncs.com/${DOCKER_USER}/lxcfs-admission-webhook:v2 .
rm -rf bin/lxcfs-admission-webhook

#docker push registry.cn-hangzhou.aliyuncs.com/${DOCKER_USER}/lxcfs-admission-webhook:v1
